name: Merritt Decorators
favicon: null
layout_spectrum: 0.4023081958293915
typography_spectrum: 0.2592265827115625
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7717821423429996
  lightness: 0.7039064450655133
  saturation: 0.6383315280545503
  rhythmicContrast: 0.23448806605301797
purpose: []
